# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:current  # https://hub.docker.com/r/cimg/node/tags
    steps:
      - checkout
      - run:
          command: |
            npm install --save-dev jest  # https://jestjs.io/docs/getting-started
            python3 run_tests.py

workflows:
  run-unit-tests:
    jobs:
      - test
